// ============================================================================
//  Levels. Grid units are metres. x runs along the facade, y is height.
//  House windows/doors are in grid coordinates (bottom-left + size).
// ============================================================================

const win = (x, floor, w = 1) => ({ x, y: floor * 3 + 0.9, w, h: 1.3 });

export const LEVELS = [
  {
    id: 1, name: 'First Lift', client: 'Mrs Pemberton, 4 Orchard Close',
    brief: 'The bungalow gutter is full of moss. Build a platform at 2 m so Dave can reach it with a couple of hods of bricks for the chimney.',
    tip: 'Click an orange dot on the ground, then another dot, to place a tube. Squares can wobble; a diagonal brace turns them into rigid triangles.',
    W: 9, H: 4,
    house: { x0: 0.5, x1: 8.5, floors: 1, eaves: 3, brick: 'red', door: { x: 5.5, w: 1, h: 2.1, color: '#2f5d50' }, windows: [win(1.2, 0, 1.4), win(3.5, 0, 1.2), win(7.0, 0, 1.0)], roof: 'gable', chimney: 2 },
    zones: [{ x0: 2, x1: 5, y: 2, label: 'Gutter' }],
    deliveries: [{ item: 'hod', zone: 0, x: 2.5 }, { item: 'hod', zone: 0, x: 4.5 }],
    budget: 330, chavs: 0, startX: 11, monster: true,
  },
  {
    id: 2, name: 'Window Dressing', client: 'The Okafors, 12 Mill Lane',
    brief: 'New sills on the first-floor windows. The platform needs to be at 4 m and run the full width of the two windows.',
    tip: 'Tall frames need bracing on every lift. Tubes can be up to 3 m long, and a long tube joins every grid point it passes.',
    W: 10, H: 6,
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'red', door: { x: 1.5, w: 1, h: 2.1, color: '#7a2230' }, windows: [win(4, 0, 1.4), win(7, 0, 1.4), win(3.3, 1, 1.4), win(6.3, 1, 1.4)], roof: 'gable', chimney: 8 },
    zones: [{ x0: 3, x1: 8, y: 4, label: 'Sills' }],
    deliveries: [{ item: 'hod', zone: 0, x: 3.5 }, { item: 'bags', zone: 0, x: 6.5 }],
    budget: 740, chavs: 1, startX: 12,
  },
  {
    id: 3, name: 'Pallet Up', client: 'Brick & Sons Builders',
    brief: 'A whole pallet of bricks is going up to 3 m. Timber boards hold about 360 kg at mid-span, and Dave plus a pallet weighs over 500 kg.',
    tip: 'Dave can\'t carry that pallet across timber boards. Run his ladder up to a standard within 1 m of the drop spot (4 m) and he\'ll heave it across from the top.',
    W: 9, H: 5,
    house: { x0: 0.5, x1: 8.5, floors: 2, eaves: 6, brick: 'yellow', door: { x: 6.5, w: 1, h: 2.1, color: '#1f3b73' }, windows: [win(2, 0, 1.2), win(2, 1, 1.2), win(4.5, 1, 1.2)], roof: 'gable', chimney: 1.5 },
    zones: [{ x0: 2, x1: 6, y: 3, label: 'Brickwork' }],
    deliveries: [{ item: 'pallet', zone: 0, x: 4 }, { item: 'hod', zone: 0, x: 2.5 }],
    budget: 540, chavs: 2, startX: 11,
  },
  {
    id: 4, name: 'Mind the Door', client: 'Rev. Hollis, The Old Vicarage',
    brief: 'The vicar must be able to get in and out. Keep the doorway clear and bridge the platform over it.',
    tip: 'A truss (a row of triangles) can span a gap that a single tube cannot.',
    W: 11, H: 6,
    house: { x0: 0.5, x1: 10.5, floors: 2, eaves: 6, brick: 'red', door: { x: 5, w: 1, h: 2.3, color: '#5b2a86' }, windows: [win(1.5, 0, 1.2), win(8.3, 0, 1.2), win(1.5, 1, 1.2), win(5, 1, 1.0), win(8.3, 1, 1.2)], roof: 'gable', chimney: 9 },
    forbidden: [{ x0: 4, y0: 0, x1: 7, y1: 3, kind: 'door', label: 'Keep clear' }],
    zones: [{ x0: 3, x1: 8, y: 4, label: 'Repointing' }],
    deliveries: [{ item: 'bags', zone: 0, x: 5.5 }, { item: 'tiles', zone: 0, x: 4 }],
    budget: 910, chavs: 2, startX: 13, monster: true,
  },
  {
    id: 5, name: 'Prize Roses', client: 'Major Thistlewood (ret.)',
    brief: "The Major's roses won Best in Show. Nothing may stand in the rose bed. Nothing.",
    tip: 'Only the ground either side of the bed can take a base plate. Ties to the wall stop sideways sway but carry no weight.',
    W: 10, H: 5,
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'red', door: { x: 8.2, w: 1, h: 2.1, color: '#b8860b' }, windows: [win(1.2, 0, 1.2), win(4.5, 0, 1.2), win(1.2, 1, 1.2), win(4.5, 1, 1.2), win(7.6, 1, 1.2)], roof: 'gable', chimney: 5 },
    noBase: [[3, 6, 'roses']],
    zones: [{ x0: 3, x1: 7, y: 3, label: 'Render' }],
    deliveries: [{ item: 'hod', zone: 0, x: 4.5 }, { item: 'bags', zone: 0, x: 5.5 }],
    budget: 980, chavs: 2, startX: 12,
  },
  {
    id: 6, name: 'Blustery Day', client: 'Hilltop Farmhouse',
    brief: 'Gutter repair on an exposed hilltop, and the wind is picking up. A half-built frame can blow over before it is braced.',
    tip: 'Build order matters. Get a braced triangle up first, then grow from it. Ties to the wall resist the wind.',
    W: 9, H: 6,
    house: { x0: 0.5, x1: 8.5, floors: 2, eaves: 6, brick: 'stone', door: { x: 1.5, w: 1, h: 2.1, color: '#3a5f2a' }, windows: [win(4.5, 0, 1.2), win(6.8, 0, 1.0), win(4.5, 1, 1.2), win(6.8, 1, 1.0)], roof: 'gable', chimney: 7.5 },
    zones: [{ x0: 2, x1: 6, y: 5, label: 'Gutter' }],
    deliveries: [{ item: 'hod', zone: 0, x: 2.5 }, { item: 'bags', zone: 0, x: 4.5 }],
    wind: 18, gust: 26, maxTies: 3,
    budget: 970, chavs: 2, startX: 11,
  },
  {
    id: 7, name: 'Listed Building', client: 'Heritage Trust',
    brief: 'Grade II listed. You may not drill the facade, so no wall ties at all. The whole scaffold must stand on its own.',
    tip: 'Without ties, a tall narrow scaffold can tip over. Spread the base wider than the platform, and brace it both ways.',
    W: 11, H: 7,
    house: { x0: 1.5, x1: 9.5, floors: 2, eaves: 6, brick: 'render', door: { x: 5, w: 1, h: 2.3, color: '#223344' }, windows: [win(2.5, 0), win(7.5, 0), win(2.5, 1), win(5, 1), win(7.5, 1)], roof: 'gable', chimney: 3 },
    zones: [{ x0: 3, x1: 8, y: 6, label: 'Cornice' }],
    deliveries: [{ item: 'tiles', zone: 0, x: 4 }, { item: 'bags', zone: 0, x: 6.5 }],
    wind: 8, gust: 10, maxTies: 0,
    budget: 1080, chavs: 3, startX: 13, monster: true,
  },
  {
    id: 8, name: 'The Lightwell', client: 'Flat B, 27 Regent Terrace',
    brief: 'A sunken basement yard runs along the front of this townhouse. The platform at 3 m must span right across it.',
    tip: 'Standards in the lightwell start 2 m lower, so they are longer and need more bracing.',
    W: 10, H: 5,
    ground: [0, 0, 0, -2, -2, -2, -2, 0, 0, 0, 0],
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'yellow', door: { x: 8, w: 1, h: 2.3, color: '#101010' }, windows: [win(1.2, 0, 1.2), win(4, 0, 1.4), win(1.2, 1, 1.2), win(4, 1, 1.4), win(7.5, 1, 1.2)], roof: 'gable', chimney: 1.5 },
    zones: [{ x0: 1, x1: 8, y: 3, label: 'Balcony' }],
    deliveries: [{ item: 'bags', zone: 0, x: 2.5 }, { item: 'mixer', zone: 0, x: 5 }, { item: 'hod', zone: 0, x: 7 }],
    budget: 940, chavs: 3, startX: 12,
  },
  {
    id: 9, name: 'Bath Time', client: 'Mr & Mrs Vasquez',
    brief: 'A cast-iron roll-top bath is going in through the first-floor window, plus a cement mixer for the new floor.',
    tip: 'Steel deck is now available. It costs more but holds 1500 kg. Mix it with timber where the loads are light.',
    W: 10, H: 5,
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'red', door: { x: 1.5, w: 1, h: 2.1, color: '#8b4513' }, windows: [win(4, 0, 1.2), win(7, 0, 1.2), win(3.3, 1, 1.4), win(7, 1, 1.2)], roof: 'gable', chimney: 8.5 },
    zones: [{ x0: 2, x1: 8, y: 4, label: 'Bathroom' }],
    deliveries: [{ item: 'bath', zone: 0, x: 4 }, { item: 'mixer', zone: 0, x: 6.5 }, { item: 'bags', zone: 0, x: 3 }],
    deck: true,
    budget: 990, chavs: 3, startX: 12,
  },
  {
    id: 10, name: 'Piano Removals', client: 'Madame Duval, Music Teacher',
    brief: 'Two pianos up to the second-floor studio at 6 m. The porch canopy below must not be touched.',
    tip: 'Heavy tubes are now available: stiffer and stronger, at more than twice the price. Use them where the big loads go down.',
    W: 11, H: 7,
    house: { x0: 0.5, x1: 10.5, floors: 3, eaves: 9, brick: 'red', door: { x: 5, w: 1, h: 2.3, color: '#1d4d4f' }, windows: [win(1.5, 0, 1.2), win(8.3, 0, 1.2), win(1.5, 1, 1.2), win(5, 1), win(8.3, 1, 1.2), win(3, 2, 1.6), win(6.8, 2, 1.6)], roof: 'gable', chimney: 2 },
    forbidden: [{ x0: 4, y0: 0, x1: 7, y1: 3, kind: 'porch', label: 'Porch' }],
    zones: [{ x0: 3, x1: 8, y: 6, label: 'Studio' }],
    deliveries: [{ item: 'piano', zone: 0, x: 4 }, { item: 'grand', zone: 0, x: 6.5 }],
    wind: 6, gust: 8, deck: true, heavy: true, maxTies: 4,
    budget: 1870, chavs: 3, startX: 13, monster: true,
  },
  {
    id: 11, name: 'Chimney Stack', client: 'Tall House, Windy Ridge',
    brief: 'The chimney pots need replacing at 8 m on a three-storey house, in a stiff breeze. Only 2 ties are allowed.',
    tip: 'Height multiplies everything: wind load, sway and the weight on the bottom lift.',
    W: 9, H: 9,
    house: { x0: 0.5, x1: 8.5, floors: 3, eaves: 9, brick: 'stone', door: { x: 1.5, w: 1, h: 2.1, color: '#4a0f0f' }, windows: [win(4.5, 0, 1.2), win(6.8, 0, 1), win(1.5, 1, 1), win(4.5, 1, 1.2), win(6.8, 1, 1), win(1.5, 2, 1), win(4.5, 2, 1.2), win(6.8, 2, 1)], roof: 'gable', chimney: 4.5 },
    zones: [{ x0: 3, x1: 6, y: 8, label: 'Chimney' }],
    deliveries: [{ item: 'hod', zone: 0, x: 3.5 }, { item: 'anvil', zone: 0, x: 5 }],
    wind: 16, gust: 24, maxTies: 2, deck: true, heavy: true,
    budget: 1020, chavs: 2, startX: 11,
  },
  {
    id: 12, name: 'Heavy Metal', client: 'Sir Reginald Crump, Crump Towers',
    brief: 'Sir Reginald is having a safe, a tonne of sand, and a life-size bronze elephant put on his first-floor terrace. Do not ask why.',
    tip: 'Every tonne needs a straight path to the ground. Put standards under the drops and decks where Dave walks.',
    W: 11, H: 5,
    house: { x0: 0.5, x1: 10.5, floors: 2, eaves: 6, brick: 'stone', door: { x: 5, w: 1.2, h: 2.4, color: '#6b0f1a' }, windows: [win(1.5, 0, 1.4), win(8, 0, 1.4), win(1.5, 1, 1.4), win(5, 1, 1.2), win(8, 1, 1.4)], roof: 'gable', chimney: 9 },
    zones: [{ x0: 2, x1: 9, y: 3, label: 'Terrace' }],
    deliveries: [{ item: 'safe', zone: 0, x: 3 }, { item: 'dumpy', zone: 0, x: 8 }, { item: 'statue', zone: 0, x: 5.5 }],
    wind: 4, gust: 6, deck: true, heavy: true,
    budget: 1520, chavs: 4, startX: 13,
  },
  // ------------------------------------------------------------------ part two
  {
    id: 13, name: 'Hoist Away', client: 'Old Corn Mill (luxury flats coming soon)',
    brief: "The developers want a sack of grain and the original millstone back up at the loft doors, 6 m up. Too heavy to carry: fit a gin wheel and haul them up on a rope.",
    tip: "The rope has to hang clear to the ground, so the wheel goes out on a cantilever past the end of the scaffold. Rope over a wheel pulls down twice the load. Brace the arm.",
    W: 10, H: 8,
    house: { style: 'mill', x0: 0.5, x1: 8.5, floors: 3, eaves: 9, brick: 'stone', door: { x: 4.2, w: 1.6, h: 2.8, color: '#3a2618', round: true }, windows: [{ x: 1.2, y: 1.0, w: 0.8, h: 1.3, kind: 'mill' }, { x: 2.6, y: 1.0, w: 0.8, h: 1.3, kind: 'mill' }, { x: 6.5, y: 1.0, w: 0.8, h: 1.3, kind: 'mill' }, { x: 7.5, y: 1.0, w: 0.8, h: 1.3, kind: 'mill' }, { x: 1.2, y: 3.7, w: 0.8, h: 1.3, kind: 'mill' }, { x: 2.6, y: 3.7, w: 0.8, h: 1.3, kind: 'mill' }, { x: 6.5, y: 3.7, w: 0.8, h: 1.3, kind: 'mill' }, { x: 7.5, y: 3.7, w: 0.8, h: 1.3, kind: 'mill' }, { x: 1.2, y: 6.7, w: 0.8, h: 1.3, kind: 'mill' }, { x: 2.6, y: 6.7, w: 0.8, h: 1.3, kind: 'mill' }, { x: 6.5, y: 6.7, w: 0.8, h: 1.3, kind: 'mill' }, { x: 7.5, y: 6.7, w: 0.8, h: 1.3, kind: 'mill' }], roof: 'gable', loadingDoors: 5, datestone: 'CORN MILL 1832' },
    zones: [{ x0: 3, x1: 7, y: 6, label: 'Loft doors' }],
    deliveries: [],
    event: { type: 'hoist', loads: ['sacks', 'millstone'] },
    heavy: true,
    budget: 1660, chavs: 1, startX: 12,
  },
  {
    id: 14, name: "Terry's 50th", client: 'The Scaffolders Arms',
    brief: "Terry's having his 50th on the scaffold outside his local. A dozen of the lads will be partying on and around the platform at 3 m. Get the beer and the speakers up first.",
    tip: 'Everyone jumps in time to the music and sways side to side together. A floppy scaffold rocks harder and harder until something gives. Braces and ties keep it stiff.',
    W: 10, H: 5,
    house: { style: 'pub', x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'render', door: { x: 4.5, w: 1.1, h: 2.2, color: '#1f3b2c' }, windows: [win(1.3, 0, 1.6), win(7, 0, 1.6), win(1.5, 1, 1.2), win(4.5, 1, 1.1), win(7.2, 1, 1.2)], roof: 'gable', chimney: 8, sign: 'THE SCAFFOLDERS ARMS' },
    zones: [{ x0: 2, x1: 8, y: 3, label: 'Dance floor' }],
    deliveries: [{ item: 'keg', zone: 0, x: 3 }, { item: 'speakers', zone: 0, x: 7 }],
    event: { type: 'party', guests: 12, dur: 20, beat: 2.0, sway: 200 },
    budget: 860, chavs: 1, startX: 12,
  },
  {
    id: 15, name: 'Sanctuary', client: 'St Wilfrid\'s Church',
    brief: "The lead's come off the nave roof. Platform at 4 m. There's something in the drains again, but you can't dig a trap door in a churchyard.",
    tip: 'When it comes, Dave climbs up and pulls his ladder up behind him. It can\'t climb, but it will shake the scaffold for all it\'s worth. Brace the bottom lift.',
    W: 11, H: 6,
    house: { style: 'church', x0: 0.5, x1: 10.5, floors: 1, eaves: 5, brick: 'stone', door: { x: 8.6, w: 1.2, h: 2.6, color: '#4a2d18', arch: true }, windows: [{ x: 1.6, y: 1.2, w: 0.9, h: 2.8, kind: 'lancet' }, { x: 4.0, y: 1.2, w: 0.9, h: 2.8, kind: 'lancet' }, { x: 6.4, y: 1.2, w: 0.9, h: 2.8, kind: 'lancet' }], roof: 'gable' },
    noBase: [[5, 5, 'graves']],
    zones: [{ x0: 3, x1: 8, y: 4, label: 'Lead flashing' }],
    deliveries: [{ item: 'hod', zone: 0, x: 4 }, { item: 'bags', zone: 0, x: 7 }],
    monster: 'hide', shake: 5000, night: true,
    budget: 960, chavs: 0, startX: 13,
  },
  {
    id: 16, name: 'Down the Chute', client: 'Brother Anselm, Kirkby Abbey',
    brief: "The roofers are stripping the old slates from the abbey roof and throwing them down onto your platform at 6 m. Get the rubble down a chute into the skip. The Bishop has parked next to it.",
    tip: "The skip is at 10½–12 m, so the chute has to hang off a board end over it. No chute and the roofers throw it off the end, onto the Bishop's car.",
    W: 12, H: 9,
    house: { style: 'abbey', x0: 0.5, x1: 10, floors: 2, eaves: 8, brick: 'stone', door: { x: 1.2, w: 1.4, h: 3, color: '#3b2616', arch: true }, windows: [{ x: 3.6, y: 1.2, w: 1.1, h: 3.2, kind: 'lancet' }, { x: 6.4, y: 1.2, w: 1.1, h: 3.2, kind: 'lancet' }, { x: 3.6, y: 5.2, w: 1.1, h: 2, kind: 'lancet' }, { x: 6.4, y: 5.2, w: 1.1, h: 2, kind: 'lancet' }], roof: 'gable' },
    zones: [{ x0: 2, x1: 10, y: 6, label: 'Roof strip' }],
    deliveries: [],
    event: { type: 'chute', bags: [3, 5, 8, 4, 9, 6], skip: [10.5, 12], car: [7.5, 10], carCost: 250 },
    budget: 2130, chavs: 2, startX: 14,
  },
  {
    id: 17, name: 'Last Orders', client: 'Nether Wallop Village Hall',
    brief: "It's the village fete, and Terry's rigged a zip wire from a platform at 5 m on the hall across the road to the pub. Three riders. The wire pulls the top of the scaffold towards the pub, hard.",
    tip: 'The pull is sideways. Diagonal braces take it to the ground, and wall ties hold the top back. The biggest pull is when a rider is halfway across.',
    W: 10, H: 6,
    house: { style: 'hall', x0: 0.5, x1: 9.5, floors: 1, eaves: 4.5, brick: 'red', door: { x: 4.4, w: 1.2, h: 2.3, color: '#2c4a7a' }, windows: [win(1.5, 0, 1.6), win(7, 0, 1.6)], roof: 'gable', sign: 'VILLAGE HALL' },
    zones: [{ x0: 5, x1: 9, y: 5, label: 'Zip wire' }],
    deliveries: [],
    event: { type: 'zip', riders: [{ style: 'terry', name: 'Terry', mass: 125 }, { style: 'sheila', name: 'Sheila', mass: 72 }, { style: 'vicar', name: 'The vicar', mass: 80 }], dx: 16, y: 1.2, sag: 1.4, pre: 700, k: 2.3 },
    budget: 1250, chavs: 1, startX: 12,
  },
  {
    id: 18, name: 'Pedal Power', client: 'Tyler (aged 12) and his mum',
    brief: "Tyler's going to ride his BMX out of the leisure centre's first-floor window at 3 m, along your platform, off the end, and into a paddling pool. His mum has agreed to this.",
    tip: 'He comes off the end at the same speed every time, so the end of the platform decides where he lands. Check the landing spot in the checklist. No gaps, no trap boards.',
    W: 12, H: 5,
    house: { style: 'leisure', x0: 0.5, x1: 8.5, floors: 2, eaves: 6, brick: 'render', door: { x: 5, w: 1.8, h: 2.2, color: '#1a6fb8' }, windows: [{ x: 1.4, y: 3.3, w: 1.4, h: 1.5 }, { x: 3.6, y: 3.3, w: 3.6, h: 1.5 }, { x: 1.4, y: 0.6, w: 3, h: 1.6 }], roof: 'flat', sign: 'LEISURE CENTRE' },
    zones: [{ x0: 2, x1: 8, y: 3, label: 'BMX track' }],
    deliveries: [{ item: 'hod', zone: 0, x: 5 }],
    event: { type: 'bmx', start: 2, pool: [16.2, 17.8], v: 6, hop: 1 },
    budget: 1210, chavs: 2, startX: 11,
  },
  {
    id: 19, name: 'Remember, Remember', client: 'The Dean, St Aldhelm\'s Cathedral',
    brief: "Terry's doing the Bonfire Night fireworks from a platform at 7 m in the cathedral close. Get the crate up. The stained glass is £300 a pane.",
    tip: 'Some rockets go wherever they like. The windows marked ⚠ are in the firing line: £35 to board up, or £300 if one goes through.',
    W: 12, H: 8,
    house: { style: 'cathedral', x0: 0.5, x1: 11.5, floors: 3, eaves: 12, brick: 'stone', door: { x: 5.2, w: 1.6, h: 3.2, color: '#3b2616', arch: true }, windows: [{ x: 1.5, y: 1.5, w: 1, h: 3.4, kind: 'lancet' }, { x: 9.5, y: 1.5, w: 1, h: 3.4, kind: 'lancet' }, { x: 2.6, y: 7.2, w: 1.1, h: 3, kind: 'lancet' }, { x: 5.3, y: 8, w: 1.4, h: 1.4, kind: 'rose' }, { x: 8.3, y: 7.2, w: 1.1, h: 3, kind: 'lancet' }], roof: 'gable' },
    zones: [{ x0: 4, x1: 8, y: 7, label: 'Launch platform' }],
    deliveries: [{ item: 'fireworks', zone: 0, x: 6 }],
    event: { type: 'fireworks', rockets: 12, launchX: 6, rogue: [-1, -1, 2, -1, -1, 4, -1, -1, 3, -1, -1, -1] },
    glazier: 300, night: true,
    budget: 1370, chavs: 2, startX: 14,
  },
  {
    id: 20, name: 'Christmas Eve', client: 'Number 7, Holly Close',
    brief: "Father Christmas is landing on your platform at 5 m tonight. The sleigh comes in from the left and skids to a stop on the snow, so it needs a long runway, and it shoves the scaffold as it brakes.",
    tip: 'The sleigh touches down at the left end of the platform. Give it a long unbroken run of real boards, and brace against the push towards the right.',
    W: 10, H: 6,
    house: { style: 'terrace', x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'red', door: { x: 4.4, w: 1, h: 2.1, color: '#8a1c2b', wreath: true }, windows: [win(1.5, 0, 1.3), win(7, 0, 1.3), win(1.5, 1, 1.3), win(7, 1, 1.3)], roof: 'gable', chimney: 6 },
    zones: [{ x0: 1, x1: 5, y: 5, label: 'Sleigh runway' }],
    deliveries: [{ item: 'presents', zone: 0, x: 4 }],
    event: { type: 'sleigh', v: 6.5, mu: 0.5, mass: 420 },
    snow: true, night: true,
    budget: 1220, chavs: 1, startX: 12,
  },
  {
    id: 21, name: 'Ring Out', client: 'The Bell Ringers\' Guild',
    brief: "The tenor bell's been recast and it's going back into the belfry at 8 m. It weighs 900 kg. The cathedral wall is fine for ties, but mind the flying buttress.",
    tip: 'Nine hundred kilos needs a straight path to the ground: heavy tube under the drop, steel deck where it lands.',
    W: 10, H: 9,
    house: { style: 'cathedral', x0: 0.5, x1: 9.5, floors: 3, eaves: 14, brick: 'stone', tower: true, door: { x: 1.2, w: 1.4, h: 3, color: '#3b2616', arch: true }, windows: [{ x: 7.4, y: 1.5, w: 1, h: 3.2, kind: 'lancet' }, { x: 4.2, y: 9.2, w: 1.6, h: 2.6, kind: 'louvre' }], roof: 'gable' },
    forbidden: [{ x0: 8, y0: 0, x1: 10, y1: 5, kind: 'buttress', label: 'Flying buttress' }],
    zones: [{ x0: 3, x1: 7, y: 8, label: 'Belfry' }],
    deliveries: [{ item: 'bell', zone: 0, x: 5 }],
    wind: 8, gust: 10, heavy: true, deck: true,
    budget: 2370, chavs: 2, startX: 12,
  },
  {
    id: 22, name: 'Glass Act', client: 'Shard & Partners, Canary Row',
    brief: 'New glass panels for the office tower at 12 m. The wind comes round the building like a train, and the only places to tie in are the floor slabs.',
    tip: 'Ties only work where the floors are, every 3 m. Three ladders to get Dave up, three platforms for him to step off. Wind grows with height.',
    W: 10, H: 13,
    house: { style: 'tower', x0: 0.5, x1: 9.5, floors: 12, eaves: 38, brick: 'render', door: { x: 4, w: 2, h: 2.4, color: '#1c2630' }, windows: [], roof: 'flat', tieRows: [3, 6, 9, 12] },
    zones: [{ x0: 2, x1: 7, y: 12, label: 'Cladding' }],
    deliveries: [{ item: 'glass', zone: 0, x: 4.5 }],
    wind: 12, gust: 14, heavy: true, deck: true,
    budget: 3040, chavs: 0, startX: 12,
  },
  {
    id: 23, name: 'Penthouse Party', client: 'Kristoff, Penthouse B',
    brief: "Kristoff's roof-terrace launch party has spilled onto your platform at 9 m. Twelve guests dancing, in the wind, nine metres up.",
    tip: 'Everything from the pub job, only higher and windier. Tie in at the floor slabs and brace every lift.',
    W: 10, H: 10,
    house: { style: 'tower', x0: 0.5, x1: 9.5, floors: 9, eaves: 30, brick: 'render', door: { x: 4, w: 2, h: 2.4, color: '#1c2630' }, windows: [], roof: 'flat', tieRows: [3, 6, 9] },
    zones: [{ x0: 2, x1: 8, y: 9, label: 'Roof terrace' }],
    deliveries: [{ item: 'keg', zone: 0, x: 3 }, { item: 'speakers', zone: 0, x: 7 }],
    event: { type: 'party', guests: 12, dur: 20, beat: 2.1, sway: 170 },
    wind: 10, gust: 12, heavy: true,
    budget: 2490, chavs: 0, startX: 12,
  },
  {
    id: 24, name: 'Launch Day', client: 'Wessex Space Agency',
    brief: "The capsule hatch is 12 m up. Build a crew access tower, get the astronaut's packed lunch up there, then stand well back. Nothing may be tied to the rocket.",
    tip: 'At ignition the exhaust blasts the whole tower sideways for several seconds. Go wide at the base, heavy tube and lots of triangles.',
    W: 12, H: 13,
    house: { style: 'rocket', x0: 0.4, x1: 2.6, floors: 0, eaves: 20, brick: 'render', windows: [], roof: 'flat' },
    zones: [{ x0: 3, x1: 6, y: 12, label: 'Capsule hatch' }],
    deliveries: [{ item: 'kit', zone: 0, x: 4 }],
    event: { type: 'launch', capsuleX: 3.3, blast: 280 },
    maxTies: 0, wind: 6, gust: 6, heavy: true, deck: true,
    budget: 4230, chavs: 0, startX: 14,
  },
];
