// ============================================================================
//  Levels. Grid units are metres. x runs along the facade, y is height.
//  House windows/doors are in grid coordinates (bottom-left + size).
// ============================================================================

const win = (x, floor, w = 1) => ({ x, y: floor * 3 + 0.9, w, h: 1.3 });

export const LEVELS = [
  {
    id: 1, name: 'First Lift', client: 'Mrs Pemberton, 4 Orchard Close',
    brief: 'The bungalow gutter is full of moss. Build a platform at 2 m so Dave can reach it with a couple of hods of bricks for the chimney.',
    tip: 'Click an orange dot on the ground, then another dot, to place a tube. Squares can wobble; a diagonal brace turns them into rigid triangles.',
    W: 9, H: 4,
    house: { x0: 0.5, x1: 8.5, floors: 1, eaves: 3, brick: 'red', door: { x: 5.5, w: 1, h: 2.1, color: '#2f5d50' }, windows: [win(1.2, 0, 1.4), win(3.5, 0, 1.2), win(7.0, 0, 1.0)], roof: 'gable', chimney: 2 },
    zones: [{ x0: 2, x1: 5, y: 2, label: 'Gutter' }],
    deliveries: [{ item: 'hod', zone: 0, x: 2.5 }, { item: 'hod', zone: 0, x: 4.5 }],
    budget: 300, chavs: 0, startX: 11,
  },
  {
    id: 2, name: 'Window Dressing', client: 'The Okafors, 12 Mill Lane',
    brief: 'New sills on the first-floor windows. The platform needs to be at 4 m and run the full width of the two windows.',
    tip: 'Tall frames need bracing on every lift. Tubes can be up to 3 m long, and a long tube joins every grid point it passes.',
    W: 10, H: 6,
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'red', door: { x: 1.5, w: 1, h: 2.1, color: '#7a2230' }, windows: [win(4, 0, 1.4), win(7, 0, 1.4), win(3.3, 1, 1.4), win(6.3, 1, 1.4)], roof: 'gable', chimney: 8 },
    zones: [{ x0: 3, x1: 8, y: 4, label: 'Sills' }],
    deliveries: [{ item: 'hod', zone: 0, x: 3.5 }, { item: 'bags', zone: 0, x: 6.5 }],
    budget: 740, chavs: 1, startX: 12,
  },
  {
    id: 3, name: 'Pallet Up', client: 'Brick & Sons Builders',
    brief: 'A whole pallet of bricks is going up to 3 m. Timber boards hold about 360 kg at mid-span, and Dave plus a pallet weighs over 500 kg.',
    tip: 'Dave climbs the standard nearest the drop spot. Put a standard right under the drop and he can heave it across without walking on the boards.',
    W: 9, H: 5,
    house: { x0: 0.5, x1: 8.5, floors: 2, eaves: 6, brick: 'yellow', door: { x: 6.5, w: 1, h: 2.1, color: '#1f3b73' }, windows: [win(2, 0, 1.2), win(2, 1, 1.2), win(4.5, 1, 1.2)], roof: 'gable', chimney: 1.5 },
    zones: [{ x0: 2, x1: 6, y: 3, label: 'Brickwork' }],
    deliveries: [{ item: 'pallet', zone: 0, x: 4 }, { item: 'hod', zone: 0, x: 2.5 }],
    budget: 540, chavs: 2, startX: 11,
  },
  {
    id: 4, name: 'Mind the Door', client: 'Rev. Hollis, The Old Vicarage',
    brief: 'The vicar must be able to get in and out. Keep the doorway clear and bridge the platform over it.',
    tip: 'A truss (a row of triangles) can span a gap that a single tube cannot.',
    W: 11, H: 6,
    house: { x0: 0.5, x1: 10.5, floors: 2, eaves: 6, brick: 'red', door: { x: 5, w: 1, h: 2.3, color: '#5b2a86' }, windows: [win(1.5, 0, 1.2), win(8.3, 0, 1.2), win(1.5, 1, 1.2), win(5, 1, 1.0), win(8.3, 1, 1.2)], roof: 'gable', chimney: 9 },
    forbidden: [{ x0: 4, y0: 0, x1: 7, y1: 3, kind: 'door', label: 'Keep clear' }],
    zones: [{ x0: 3, x1: 8, y: 4, label: 'Repointing' }],
    deliveries: [{ item: 'bags', zone: 0, x: 5.5 }, { item: 'tiles', zone: 0, x: 4 }],
    budget: 880, chavs: 2, startX: 13,
  },
  {
    id: 5, name: 'Prize Roses', client: 'Major Thistlewood (ret.)',
    brief: "The Major's roses won Best in Show. Nothing may stand in the rose bed. Nothing.",
    tip: 'Only the ground either side of the bed can take a base plate. Ties to the wall stop sideways sway but carry no weight.',
    W: 10, H: 5,
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'red', door: { x: 8.2, w: 1, h: 2.1, color: '#b8860b' }, windows: [win(1.2, 0, 1.2), win(4.5, 0, 1.2), win(1.2, 1, 1.2), win(4.5, 1, 1.2), win(7.6, 1, 1.2)], roof: 'gable', chimney: 5 },
    noBase: [[3, 6, 'roses']],
    zones: [{ x0: 3, x1: 7, y: 3, label: 'Render' }],
    deliveries: [{ item: 'hod', zone: 0, x: 4.5 }, { item: 'bags', zone: 0, x: 5.5 }],
    budget: 980, chavs: 2, startX: 12,
  },
  {
    id: 6, name: 'Blustery Day', client: 'Hilltop Farmhouse',
    brief: 'Gutter repair on an exposed hilltop, and the wind is picking up. A half-built frame can blow over before it is braced.',
    tip: 'Build order matters. Get a braced triangle up first, then grow from it. Ties to the wall resist the wind.',
    W: 9, H: 6,
    house: { x0: 0.5, x1: 8.5, floors: 2, eaves: 6, brick: 'stone', door: { x: 1.5, w: 1, h: 2.1, color: '#3a5f2a' }, windows: [win(4.5, 0, 1.2), win(6.8, 0, 1.0), win(4.5, 1, 1.2), win(6.8, 1, 1.0)], roof: 'gable', chimney: 7.5 },
    zones: [{ x0: 2, x1: 6, y: 5, label: 'Gutter' }],
    deliveries: [{ item: 'hod', zone: 0, x: 2.5 }, { item: 'bags', zone: 0, x: 4.5 }],
    wind: 18, gust: 26, maxTies: 3,
    budget: 970, chavs: 2, startX: 11,
  },
  {
    id: 7, name: 'Listed Building', client: 'Heritage Trust',
    brief: 'Grade II listed. You may not drill the facade, so no wall ties at all. The whole scaffold must stand on its own.',
    tip: 'Without ties, a tall narrow scaffold can tip over. Spread the base wider than the platform, and brace it both ways.',
    W: 11, H: 7,
    house: { x0: 1.5, x1: 9.5, floors: 2, eaves: 6, brick: 'render', door: { x: 5, w: 1, h: 2.3, color: '#223344' }, windows: [win(2.5, 0), win(7.5, 0), win(2.5, 1), win(5, 1), win(7.5, 1)], roof: 'gable', chimney: 3 },
    zones: [{ x0: 3, x1: 8, y: 6, label: 'Cornice' }],
    deliveries: [{ item: 'tiles', zone: 0, x: 4 }, { item: 'bags', zone: 0, x: 6.5 }],
    wind: 8, gust: 10, maxTies: 0,
    budget: 1050, chavs: 3, startX: 13,
  },
  {
    id: 8, name: 'The Lightwell', client: 'Flat B, 27 Regent Terrace',
    brief: 'A sunken basement yard runs along the front of this townhouse. The platform at 3 m must span right across it.',
    tip: 'Standards in the lightwell start 2 m lower, so they are longer and need more bracing.',
    W: 10, H: 5,
    ground: [0, 0, 0, -2, -2, -2, -2, 0, 0, 0, 0],
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'yellow', door: { x: 8, w: 1, h: 2.3, color: '#101010' }, windows: [win(1.2, 0, 1.2), win(4, 0, 1.4), win(1.2, 1, 1.2), win(4, 1, 1.4), win(7.5, 1, 1.2)], roof: 'gable', chimney: 1.5 },
    zones: [{ x0: 1, x1: 8, y: 3, label: 'Balcony' }],
    deliveries: [{ item: 'bags', zone: 0, x: 2.5 }, { item: 'mixer', zone: 0, x: 5 }, { item: 'hod', zone: 0, x: 7 }],
    budget: 940, chavs: 3, startX: 12,
  },
  {
    id: 9, name: 'Bath Time', client: 'Mr & Mrs Vasquez',
    brief: 'A cast-iron roll-top bath is going in through the first-floor window, plus a cement mixer for the new floor.',
    tip: 'Steel deck is now available. It costs more but holds 1500 kg. Mix it with timber where the loads are light.',
    W: 10, H: 5,
    house: { x0: 0.5, x1: 9.5, floors: 2, eaves: 6, brick: 'red', door: { x: 1.5, w: 1, h: 2.1, color: '#8b4513' }, windows: [win(4, 0, 1.2), win(7, 0, 1.2), win(3.3, 1, 1.4), win(7, 1, 1.2)], roof: 'gable', chimney: 8.5 },
    zones: [{ x0: 2, x1: 8, y: 4, label: 'Bathroom' }],
    deliveries: [{ item: 'bath', zone: 0, x: 4 }, { item: 'mixer', zone: 0, x: 6.5 }, { item: 'bags', zone: 0, x: 3 }],
    deck: true,
    budget: 990, chavs: 3, startX: 12,
  },
  {
    id: 10, name: 'Piano Removals', client: 'Madame Duval, Music Teacher',
    brief: 'Two pianos up to the second-floor studio at 6 m. The porch canopy below must not be touched.',
    tip: 'Heavy tubes are now available: stiffer and stronger, at more than twice the price. Use them where the big loads go down.',
    W: 11, H: 7,
    house: { x0: 0.5, x1: 10.5, floors: 3, eaves: 9, brick: 'red', door: { x: 5, w: 1, h: 2.3, color: '#1d4d4f' }, windows: [win(1.5, 0, 1.2), win(8.3, 0, 1.2), win(1.5, 1, 1.2), win(5, 1), win(8.3, 1, 1.2), win(3, 2, 1.6), win(6.8, 2, 1.6)], roof: 'gable', chimney: 2 },
    forbidden: [{ x0: 4, y0: 0, x1: 7, y1: 3, kind: 'porch', label: 'Porch' }],
    zones: [{ x0: 3, x1: 8, y: 6, label: 'Studio' }],
    deliveries: [{ item: 'piano', zone: 0, x: 4 }, { item: 'grand', zone: 0, x: 6.5 }],
    wind: 6, gust: 8, deck: true, heavy: true, maxTies: 4,
    budget: 1840, chavs: 3, startX: 13,
  },
  {
    id: 11, name: 'Chimney Stack', client: 'Tall House, Windy Ridge',
    brief: 'The chimney pots need replacing at 8 m on a three-storey house, in a stiff breeze. Only 2 ties are allowed.',
    tip: 'Height multiplies everything: wind load, sway and the weight on the bottom lift.',
    W: 9, H: 9,
    house: { x0: 0.5, x1: 8.5, floors: 3, eaves: 9, brick: 'stone', door: { x: 1.5, w: 1, h: 2.1, color: '#4a0f0f' }, windows: [win(4.5, 0, 1.2), win(6.8, 0, 1), win(1.5, 1, 1), win(4.5, 1, 1.2), win(6.8, 1, 1), win(1.5, 2, 1), win(4.5, 2, 1.2), win(6.8, 2, 1)], roof: 'gable', chimney: 4.5 },
    zones: [{ x0: 3, x1: 6, y: 8, label: 'Chimney' }],
    deliveries: [{ item: 'hod', zone: 0, x: 3.5 }, { item: 'anvil', zone: 0, x: 5 }],
    wind: 16, gust: 24, maxTies: 2, deck: true, heavy: true,
    budget: 1020, chavs: 2, startX: 11,
  },
  {
    id: 12, name: 'Heavy Metal', client: 'Sir Reginald Crump, Crump Towers',
    brief: 'Sir Reginald is having a safe, a tonne of sand, and a life-size bronze elephant put on his first-floor terrace. Do not ask why.',
    tip: 'Every tonne needs a straight path to the ground. Put standards under the drops and decks where Dave walks.',
    W: 11, H: 5,
    house: { x0: 0.5, x1: 10.5, floors: 2, eaves: 6, brick: 'stone', door: { x: 5, w: 1.2, h: 2.4, color: '#6b0f1a' }, windows: [win(1.5, 0, 1.4), win(8, 0, 1.4), win(1.5, 1, 1.4), win(5, 1, 1.2), win(8, 1, 1.4)], roof: 'gable', chimney: 9 },
    zones: [{ x0: 2, x1: 9, y: 3, label: 'Terrace' }],
    deliveries: [{ item: 'safe', zone: 0, x: 3 }, { item: 'dumpy', zone: 0, x: 8 }, { item: 'statue', zone: 0, x: 5.5 }],
    wind: 4, gust: 6, deck: true, heavy: true,
    budget: 1520, chavs: 4, startX: 13,
  },
];
